import type { SidebarsConfig } from '@cbnventures/docusaurus-preset-nova/types/sidebars';

/**
 * Sidebars Configuration.
 *
 * @since 0.11.0
 */
const config: SidebarsConfig = {
  docs: [{
    type: 'autogenerated',
    dirName: '.',
  }],
};

export default config;
