import _ from 'lodash';
import React, { useEffect, useState } from 'react';

import { styles } from '../styles/components/fingerprint-table.js';

import type {
  FingerprintTableParsedObject,
  FingerprintTableParsedObjectState,
  FingerprintTableProps,
  FingerprintTableProps_Fingerprint,
  FingerprintTableRenderTable,
  FingerprintTableRenderTableData,
  FingerprintTableRenderTableProperty,
  FingerprintTableRenderTablePropertyProperties,
  FingerprintTableRenderTablePropertyProperty,
  FingerprintTableRenderTablePropertyReturns,
  FingerprintTableRenderTableReturns,
  FingerprintTableRenderTableValue,
  FingerprintTableRenderTableValueItems,
  FingerprintTableRenderTableValueProperty,
  FingerprintTableRenderTableValueReturns,
  FingerprintTableRenderTableValueValue,
  FingerprintTableSetParsedObject,
  FingerprintTableSetStatus,
  FingerprintTableStatus,
  FingerprintTableStatusState,
} from '../types/config-ui.d.ts';

/**
 * Components - Fingerprint Table - Fingerprint Table.
 *
 * Decodes the base64 fingerprint generated by the setup wizard and lays it out
 * as a readable table so users can review the device identity data that is sent
 * to ADT Pulse without decoding it themselves.
 *
 * @constructor
 *
 * @since 1.0.0
 */
function FingerprintTable(props: FingerprintTableProps) {
  const fingerprint: FingerprintTableProps_Fingerprint = props['fingerprint'];

  const parsedObjectState: FingerprintTableParsedObjectState = useState<FingerprintTableParsedObject>({});
  const parsedObject: FingerprintTableParsedObject = parsedObjectState[0];
  const setParsedObject: FingerprintTableSetParsedObject = parsedObjectState[1];
  const statusState: FingerprintTableStatusState = useState<FingerprintTableStatus>('loading');
  const status: FingerprintTableStatus = statusState[0];
  const setStatus: FingerprintTableSetStatus = statusState[1];

  /**
   * Components - Fingerprint Table - Fingerprint Table - Render Table Property.
   *
   * Maps raw fingerprint property keys to human readable labels so the table
   * stays understandable, falling back to the original key when no label exists.
   *
   * @param {FingerprintTableRenderTablePropertyProperty} property - Property.
   *
   * @returns {FingerprintTableRenderTablePropertyReturns}
   *
   * @since 1.0.0
   */
  const renderTableProperty: FingerprintTableRenderTableProperty = (property: FingerprintTableRenderTablePropertyProperty): FingerprintTableRenderTablePropertyReturns => {
    const properties: FingerprintTableRenderTablePropertyProperties = {
      adBlock: 'Blocking Ads',
      addBehavior: 'Add Behaviour Support (IE only)',
      architecture: 'Architecture',
      availableScreenResolution: 'Available Screen Resolution',
      canvas: 'Canvas',
      colorDepth: 'Color Depth',
      cookieSupport: 'Cookie Support',
      cpuClass: 'CPU Class',
      doNotTrack: 'Do Not Track',
      fonts: 'Fonts',
      indexedDb: 'IndexedDB Support',
      language: 'Language',
      localStorage: 'Local Storage Support',
      major: 'Major',
      maxTouchPoints: 'Max Touch Points',
      model: 'Model',
      name: 'Name',
      openDatabase: 'Web SQL Database Support',
      pixelRatio: 'Pixel Ratio',
      platform: 'Platform',
      plugins: 'Plugins',
      screenResolution: 'Screen Resolution',
      sessionStorage: 'Session Storage Support',
      timezone: 'Time Zone',
      timezoneOffset: 'Time Zone (UTC Offset)',
      touchEvent: 'Touch Event',
      touchStart: 'Touch Start',
      touchSupport: 'Touch Support',
      type: 'Type',
      uaBrowser: 'Browser',
      uaCPU: 'CPU',
      uaDevice: 'Device',
      uaEngine: 'Browser Engine',
      uaOS: 'Operating System',
      uaPlatform: 'Platform',
      uaString: 'User Agent',
      userTamperBrowser: 'Tampered - Browser',
      userTamperLanguage: 'Tampered - Language',
      userTamperOS: 'Tampered - Operating System',
      userTamperScreenResolution: 'Tampered - Screen Resolution',
      vendor: 'Vendor',
      version: 'Version',
      webGl: 'WebGL',
    };

    return _.get(properties, [property], property);
  };

  /**
   * Components - Fingerprint Table - Fingerprint Table - Render Table Value.
   *
   * Formats raw fingerprint values for display, expanding comma-delimited lists
   * into list groups and translating null and boolean values into friendly text.
   *
   * @param {FingerprintTableRenderTableValueProperty} property - Property.
   * @param {FingerprintTableRenderTableValueValue}    value    - Value.
   *
   * @returns {FingerprintTableRenderTableValueReturns}
   *
   * @since 1.0.0
   */
  const renderTableValue: FingerprintTableRenderTableValue = (property: FingerprintTableRenderTableValueProperty, value: FingerprintTableRenderTableValueValue): FingerprintTableRenderTableValueReturns => {
    if (typeof value === 'string') {
      // If the selected properties have a comma-delimited list.
      if ([
        'fonts',
        'plugins',
      ].includes(property) === true) {
        const items: FingerprintTableRenderTableValueItems = value.split(',').map((item) => item.trim()).filter((item) => item.length > 0);

        return (
          <ul className="list-group">
            {
              items.map((item) => (
                <li key={item} className="list-group-item">{item}</li>
              ))
            }
          </ul>
        );
      }

      return value;
    }

    // If the value does not exist.
    if (value === null) {
      return 'N/A';
    }

    // If value is "true".
    if (value === true) {
      return 'Yes';
    }

    // If value is "false".
    if (value === false) {
      return 'No';
    }

    return JSON.stringify(value);
  };

  /**
   * Components - Fingerprint Table - Fingerprint Table - Render Table.
   *
   * Recursively builds nested tables from the parsed fingerprint object so that
   * deeply nested device details remain organized instead of being shown as JSON.
   *
   * @param {FingerprintTableRenderTableData} data - Data.
   *
   * @returns {FingerprintTableRenderTableReturns}
   *
   * @since 1.0.0
   */
  const renderTable: FingerprintTableRenderTable = (data: FingerprintTableRenderTableData): FingerprintTableRenderTableReturns => {
    if (typeof data !== 'object' || data === null) {
      return <td>{data}</td>;
    }

    return (
      <table className="table table-bordered mb-0">
        <tbody>
          {
            Object.entries(data).map((dataEntry) => (
              <tr key={dataEntry[0]}>
                <th scope="row" style={styles['tableHead']}>{renderTableProperty(dataEntry[0])}</th>
                <td>
                  {
                    (typeof dataEntry[1] === 'object' && dataEntry[1] !== null) ? (
                      renderTable(dataEntry[1])
                    ) : (
                      renderTableValue(dataEntry[0], dataEntry[1])
                    )
                  }
                </td>
              </tr>
            ))
          }
        </tbody>
      </table>
    );
  };

  useEffect(() => {
    try {
      const parsedFingerprint: FingerprintTableParsedObject = JSON.parse(atob(fingerprint));

      // Valid fingerprints are always a plain object.
      if (_.isPlainObject(parsedFingerprint) === false) {
        setStatus('failed');

        return;
      }

      setParsedObject(parsedFingerprint);
      setStatus('success');
    } catch {
      setStatus('failed');
    }

    return;
  }, [
    fingerprint,
    setParsedObject,
    setStatus,
  ]);

  // If parsing is successful.
  if (status === 'success') {
    return (
      <>
        <p className="alert alert-warning">The information shown below is for your eyes only. Fingerprints are considered your secondary password. Leaking this will compromise the MFA security to your ADT Pulse account.</p>
        <div className="table-responsive">
          {
            renderTable(_.get(parsedObject, ['fingerprint']))
          }
        </div>
      </>
    );
  }

  // If parsing has failed.
  if (status === 'failed') {
    return (
      <p className="alert alert-danger">Failed to parse your fingerprint. Please re-run the setup wizard.</p>
    );
  }

  return (
    <p className="alert alert-info">Parsing your fingerprint, please wait...</p>
  );
}

export default FingerprintTable;
