name: Bug Report
description: Found an unexpected issue or problem? Report it here.
title: "[Bug]: "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: I truly appreciate you taking the time to share this bug report with me.
  - type: markdown
    attributes:
      value: Please __fill out the form with as much detail as possible__ so I can easily recreate the bug and work swiftly to assist you in resolving it. Thank you for your cooperation!
  - type: markdown
    attributes:
      value: ---
  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-check confirmation
      description: Before proceeding further, please confirm the following by checking each box. This confirmation is crucial for me to effectively identify and address the bug. __All boxes MUST be checked; failure to comply will result in the immediate closure of this bug report.__
      options:
        - label: I have provided a descriptive title for the bug I am currently having
          required: true
        - label: "I have kept the original title prefix, __\"[Bug]: \"__"
          required: true
        - label: I have read the `README.md` file, and this is __NOT__ a duplicate bug report
          required: true
        - label: I am __NOT__ requesting a new feature
          required: true
        - label: I am not requesting help that is related to a support request
          required: true
        - label: I am using the latest version of the plugin
          required: true
  - type: input
    id: email
    attributes:
      label: Your email address
      description: Help me easily get in touch with you if I need more information. __If possible, please consider using an alias you have access to as this information is publicly visible.__
      placeholder: e.g. user@example.com
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Tell me exactly what happened
      description: Provide a comprehensive description of __the steps or circumstances__ that led to the occurrence of this bug.
      placeholder: e.g. When I was doing ..., I expected ... to happen, but I got ... instead.
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      description: What version of the plugin are you using? If you are using the Homebridge Config UI, you may find this information in the "Plugins" tab, or inside the logs that looks like `[1/1/2024, 12:00:00 AM] [ADT Pulse] running on` (shown when Homebridge starts).
      placeholder: e.g. 3.0.0
    validations:
      required: true
  - type: input
    id: homebridge-version
    attributes:
      label: Homebridge version
      description: What version of Homebridge are you using? You may find this information in the "System Information" widget when using the Homebridge Config UI or by running the `homebridge -V` command.
      placeholder: e.g. 1.7.0
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js® version
      description: What version of Node.js® are you using? __Using a version with the latest features may not be supported.__ It is recommended that you use versions that are "Recommended for Most Users" or under "Long Term Support (LTS)" as listed in the [Node.js®](https://nodejs.org) homepage.
      placeholder: e.g. 20.10.0
    validations:
      required: true
  - type: textarea
    id: test-api-output
    attributes:
      label: Output of the "test-api" command
      description: From your Homebridge plugin path, based on your [installation](https://github.com/mrjackyliang/homebridge-adt-pulse#api-test-and-repl-playground-scripts), find the `node_modules/homebridge-adt-pulse` folder, run this command `npm run test-api`, and paste in the results below. __Do not include information from other commands.__ This block will be automatically formatted into code, so __no need for backticks__.
      placeholder: Paste the full results of the "test-api" command here. If this is filled with other content (e.g. cannot find command), this bug report will be closed immediately.
      render: Shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Captured logs relevant to this report
      description: Copy and paste all logs related to this bug. __Do not include logs unrelated to this project.__ This block will be automatically formatted into code, so __no need for backticks__ or special markup.
      placeholder: Please include logs relevant to this bug report. If this is filled with miscellaneous content (e.g. no logs, cannot find logs), this bug report will be closed immediately.
      render: Shell
    validations:
      required: true
  - type: checkboxes
    id: post-check
    attributes:
      label: Post-check confirmation
      description: Before proceeding further, please confirm the following by checking each box. This confirmation is crucial for the consideration of your request. __All boxes MUST be checked; failure to comply will result in your request being closed.__
      options:
        - label: I have filled in the form __exactly as requested__ and did not attempt to circumvent form validation
          required: true
  - type: checkboxes
    id: legal
    attributes:
      label: Legal Agreements
      description: By submitting a new bug report, you confirm that you have read, understood, and agree to the [Terms of Use](https://www.cbnventures.io/terms/) and [Privacy Policy](https://www.cbnventures.io/privacy/). If you have questions about these policies, feel free to [get in touch](https://www.cbnventures.io/get-in-touch/) with my team.
      options:
        - label: I agree to the Terms of Use and Privacy Policy
          required: true
