name: "Publish to npm registries"

run-name: "Publishing ${{ github.event.release.tag_name }} to npm registries"

on:
  release:
    types: [ "published" ]

permissions:
  contents: "read"
  id-token: "write"
  packages: "write"

jobs:
  publish-to-npm-registries:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    env:
      WORKING_DIR: "./"
    strategy:
      fail-fast: false
      matrix:
        registries:
          - name: "npm"
            registry: "https://registry.npmjs.org"
          - name: "GitHub Packages"
            registry: "https://npm.pkg.github.com"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v5"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v6"
        with:
          node-version-file: "${{ env.WORKING_DIR }}/package.json"
          package-manager-cache: false
          registry-url: "${{ matrix.registries.registry }}"

      - name: "Strip deprecated npm config"
        run: "npmrc=\"${NPM_CONFIG_USERCONFIG:-$HOME/.npmrc}\" && if [ -f \"$npmrc\" ]; then sed -i '/^always-auth=/d' \"$npmrc\"; fi"

      - name: "Update npm"
        run: "npm install -g npm@latest"
        working-directory: "${{ env.WORKING_DIR }}"

      - name: "Install packages"
        run: "npm install"
        working-directory: "${{ env.WORKING_DIR }}"

      - name: "Build project"
        run: "npm run build"
        working-directory: "${{ env.WORKING_DIR }}"

      - name: "Set GitHub Packages Auth"
        if: ${{ matrix.registries.name == 'GitHub Packages' }}
        run: "echo \"NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}\" >> \"$GITHUB_ENV\""

      - name: "Publish package"
        run: "npm publish"
        working-directory: "${{ env.WORKING_DIR }}"
